# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('content', models.TextField(verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 29, 13, 59, 43, 175673), verbose_name='Опубликована')),
            ],
            options={
                'ordering': ['-posted'],
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
    ]
