# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20161129_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 29, 21, 51, 38, 249555, tzinfo=utc), verbose_name='Опубликована'),
        ),
    ]
