# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='goods/list', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name_plural': 'товары',
                'verbose_name': 'товар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/detail', verbose_name='Дополнительное изображение')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Good')),
            ],
            options={
                'verbose_name_plural': 'изображения к товару',
                'verbose_name': 'изображение к товару',
            },
        ),
    ]
